[versions]
gson = "2.10.1"
googleServices = "4.4.2"

[libraries]
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
